(function() {var implementors = {};
implementors["simple_chart"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='simple_chart/macros/struct.Formula.html' title='simple_chart::macros::Formula'>Formula</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='simple_chart/chart/struct.Point.html' title='simple_chart::chart::Point'>Point</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='simple_chart/chart/struct.DisplayPoint.html' title='simple_chart::chart::DisplayPoint'>DisplayPoint</a>","impl&lt;T:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + <a class='trait' href='simple_chart/chart/trait.IterInPoint.html' title='simple_chart::chart::IterInPoint'>IterInPoint</a>&lt;P,&nbsp;Item=P&gt;,&nbsp;P:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + <a class='trait' href='simple_chart/chart/trait.InPoint.html' title='simple_chart::chart::InPoint'>InPoint</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='simple_chart/chart/struct.Serie.html' title='simple_chart::chart::Serie'>Serie</a>&lt;T,&nbsp;P&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='simple_chart/struct.Axis.html' title='simple_chart::Axis'>Axis</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
