(function() {var implementors = {};
implementors["quick_error"] = ["impl&lt;X:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>,&nbsp;E:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='quick_error/struct.Context.html' title='quick_error::Context'>Context</a>&lt;X,&nbsp;E&gt;",];implementors["simple_chart"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='simple_chart/chart/enum.GraphError.html' title='simple_chart::chart::GraphError'>GraphError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/chart/struct.DisplayPoint.html' title='simple_chart::chart::DisplayPoint'>DisplayPoint</a>","impl&lt;T:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> + <a class='trait' href='simple_chart/chart/trait.IterInPoint.html' title='simple_chart::chart::IterInPoint'>IterInPoint</a>&lt;P,&nbsp;Item=P&gt;,&nbsp;P:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> + <a class='trait' href='simple_chart/chart/trait.InPoint.html' title='simple_chart::chart::InPoint'>InPoint</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/chart/struct.Serie.html' title='simple_chart::chart::Serie'>Serie</a>&lt;T,&nbsp;P&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/chart/struct.Chart.html' title='simple_chart::chart::Chart'>Chart</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/bitmap/struct.BitMap.html' title='simple_chart::bitmap::BitMap'>BitMap</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/bitmap/struct.Color.html' title='simple_chart::bitmap::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='simple_chart/struct.Axis.html' title='simple_chart::Axis'>Axis</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
